### ISSUE TITLE
attempted to set version twice

### ISSUE THREAD

**Issue by salva** [salva/p5-Math-Int64#9]
@autarch,

I can't build Math::Int64 using `dzil`, I get the following error.

```
$ dzil build
[DZ] beginning to build Math-Int64
[DZ] guessing dist's main_module is lib/Math/Int64.pm
[DZ] attempted to set version twice
[DZ] attempted to set version twice at /usr/lib/x86_64-linux-gnu/perl5/5.20/Moose/Meta/Method/Delegation.pm line 109.
```

My Dist::Zilla knownledge is quite limited, could you take a look at this issue, please?

**Comment by autarch** [comment]
Sorry about that. I made some changes to my dzil bundle that caused this. Fixed by fda9c795804dffca8406e5468289e99c6676d1fd
